export const downloaderDefaults = {
	concurrency: 12,
	retries: 3,
	timeoutMs: 15_000,
	retryBackoffMs: 250,
	userAgent: 'av-downloader/0.0',
	sniff: true,
	maxMisses: 8,
	scriptLimit: 20,
	startSequence: 0,
	endSequence: 0,
	overwrite: false,
	keepMergedTs: false,
	out: 'output.mp4',
	workdir: 'tmp_download',
} as const;
